[coordinates]
#window
window_top_left = [484,55]
window_width = 792
window_height = 600
#general
tab = [869, 40]
center = [880, 320]
menu_party = [930, 263]
party_lead = [724, 228] # + 110 down + 400 right
party_exit = [1165, 200]
party_v_offset = 100
party_h_offset = 300

#misc
reel_button = [880, 540]

#combat
fight_button = [650, 500]
run_button = [1100, 500]
attack = [659, 445]
attack_offset = 150
cancel_replace_move = [1315, 420]
gif_top_left = [950, 255]
gif_width = 100
gif_height = 85

#pokecenter
healing = [1423, 260]
yes_button = [1709, 200]

[doodle_info]
party_moves = [
  [30, 25, 25, 20],
  [30, 25, 25, 20],
  [30, 25, 20, 15],
  [20, 20, 10, 10],
  [30, 20, 15, 10],
  [30, 20, 15, 10],
]

# party_moves = [
#     [0, 0, 0, 0],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0],
#     [0, 0, 0, 0]
# ]
